files:
  - source: /Original/CustomBattle/std_*.xml
    translation: /Modules/UkrainianLocalization/ModuleData/Languages/%two_letters_code%/CustomBattle/%file_name%.%file_extension%
    content_segmentation: 0
    translatable_elements:
      - '/base/strings/string[@text]'
  - source: /Original/DedicatedCustomServerHelper/std_*.xml
    translation: /Modules/UkrainianLocalization/ModuleData/Languages/%two_letters_code%/DedicatedCustomServerHelper/%file_name%.%file_extension%
    content_segmentation: 0
    translatable_elements:
      - '/base/strings/string[@text]'
  - source: /Original/Native/std_*.xml
    translation: /Modules/UkrainianLocalization/ModuleData/Languages/%two_letters_code%/Native/%file_name%.%file_extension%
    content_segmentation: 0
    translatable_elements:
      - '/base/strings/string[@text]'
  - source: /Original/SandBox/std_*.xml
    translation: /Modules/UkrainianLocalization/ModuleData/Languages/%two_letters_code%/SandBox/%file_name%.%file_extension%
    content_segmentation: 0
    translatable_elements:
      - '/base/strings/string[@text]'
  - source: /Original/SandBoxCore/std_*.xml
    translation: /Modules/UkrainianLocalization/ModuleData/Languages/%two_letters_code%/SandBoxCore/%file_name%.%file_extension%
    content_segmentation: 0
    translatable_elements:
      - '/base/strings/string[@text]'
  - source: /Original/StoryMode/std_*.xml
    translation: /Modules/UkrainianLocalization/ModuleData/Languages/%two_letters_code%/StoryMode/%file_name%.%file_extension%
    content_segmentation: 0
    translatable_elements:
      - '/base/strings/string[@text]'
